Add -fgnu89-inline to CFLAGS
In GCC 5.1 default C standard changed to -std=gnu11. This changed behavior of
inline functions. Build error is:
[  198s] ./.libs/libtzplatform-config-2.0.so: undefined reference to `initialize'
[  198s] ./.libs/libtzplatform-config-2.0.so: undefined reference to `hashid'
[  198s] ./.libs/libtzplatform-config-2.0.so: undefined reference to `get_uid'
[  198s] collect2: error: ld returned 1 exit status

Changing back to gnu89 inlining mode fixes the issue.

Change-Id: I078c318857455a3a4227667670227bedb24fbc73
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>